- task: Bash@3
  inputs:
   targetType: 'inline'
   script: |
    i=0
        while [ $i -lt 30 ]
        do
            curl --location --request POST 'https://dev.armorcode.ai/client/buildvalidation' --header 'Content-Type: application/json' --header 'Authorization: Bearer 1a4a8d3f-4db4-4920-9e12-cfc9f93ac820'  -d '{ "env": "Production", "product": "418", "subProduct": "702", "buildTool":"AZURE_PIPELINE", "buildNumber": "$(Build.BuildId)"}' > result.json
            status=$(jq -r '.status' result.json)
            if [ $status = "HOLD" ]
            then
                sleep 10
                i=$(( $i + 1 ))
                if [ $i = 30 ]
                then
                    exit 1
                else
                    continue
                fi
            else
                break
            fi
        done